version: '3.5'
services:
  app:
    build:
      context: .
    image: app
    links:
      - postgres
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=passw0rd
