{{- if and .Values.ingress.enabled .Values.ingress.tls -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "django-app.fullname" . }}
  labels:
    app: {{ template "django-app.name" . }}
    chart: {{ template "django-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.deploy.host }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.deploy.host }}
{{- end -}}
