apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "django-app.fullname" . }}-db-migration
spec:
  template:
    spec:
      containers:
        - name: {{ template "django-app.fullname" . }}-db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash","-c","python3 manage.py migrate"]
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser }}

            - name: SECRET_KEY
              value: {{ .Values.deploy.secretKey | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresPassword }}

            - name: POSTGRES_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}

      restartPolicy: OnFailure
  backoffLimit: 5
