apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "postgres.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postgres.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRES_USER
            value: {{ default "" .Values.postgresqlUsername | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ default "" .Values.postgresqlPassword | quote }}
          - name: POSTGRES_DB
            value: {{ default "" .Values.postgresqlDatabase | quote }}
          ports:
            - containerPort: 5432
