---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: reference-app

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: reference-app
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "list"
    - "create"
    - "patch"
    - "update"
  - apiGroups:
    - ""
    resources:
    - "namespaces"
    verbs:
    - "list"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: reference-app
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: reference-app
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
