---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: demo-cert
  namespace: ${K8S_NAMESPACE}
spec:
  acme:
    config:
    - domains:
      - ${K8S_NAMESPACE}.apps.${K8S_CLUSTER_NAME}
      http01:
        ingressClass: nginx
  dnsNames:
  - ${K8S_NAMESPACE}.apps.${K8S_CLUSTER_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: demo-cert
