---
kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: django-ref-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

