apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: ks-dev
      server: https://api.cloud-platforms-test.k8s.integration.dsd.io
    k8sVersion: v1.9.0
    path: default
kind: ksonnet.io/app
name: django-reference-app
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
